---
argument_specs:
  # ./roles/edpm_cisco_neutron_opflex/tasks/main.yml entry point
  main:
    short_description: The main entry point for the edpm_cisco_neutron_opflex role.
    options:
       edpm_cisco_neutron_opflex_images_download_delay:
        type: int
        default: 5
        description: The seconds between retries for failed download tasks
      edpm_cisco_neutron_opflex_images_download_retries:
        type: int
        default: 5
        description: The number of retries for failed download tasks
      edpm_cisco_neutron_opflex_agent_config_src:
        default: "/var/lib/openstack/configs/cisco-neutron-opflex"
        description: |
          The path to the directory containing source of the Neutron DHCP
          agent configs.
        type: str
      edpm_cisco_neutron_opflex_agent_config_dir:
        default: "/var/lib/config-data/ansible-generated/cisco-neutron-opflex-agent"
        description: |
          The path to the directory containing Neutron DHCP agent config
          files.
        type: str
      edpm_cisco_neutron_opflex_agent_lib_dir:
        default: "/var/lib/neutron"
        description: |
          The path to the directory containing files required by the Neutron DHCP
          agent, like e.g. sidecar container wrappers.
        type: str
      edpm_cisco_neutron_opflex_image:
        default: "quay.io/podified-antelope-centos9/openstack-cisco-neutron-opflex-agent:current-podified"
        description: Neutron DHCP agent container image.
        type: str
      edpm_cisco_neutron_opflex_common_volumes:
        default:
          - /run/netns:/run/netns:shared
          - "{{ edpm_neutron_opflex_agent_config_dir }}:/etc/neutron.conf.d:z"
          - "{{ edpm_neutron_opflex_agent_lib_dir }}:/var/lib/neutron:shared,z"
          - /var/lib/kolla/config_files/neutron_opflex_agent.json:/var/lib/kolla/config_files/config.json:ro
          - /run/openvswitch:/run/openvswitch:shared,z
          - "{{ edpm_neutron_opflex_agent_lib_dir }}/opflex_agent_haproxy_wrapper:/usr/local/bin/haproxy:ro"
          - "{{ edpm_neutron_opflex_agent_lib_dir }}/kill_scripts:/etc/neutron/kill_scripts:ro"
          - /var/lib/opflex/files/endpoints:/var/lib/opflex-agent-ovs/endpoints:shared,z
          - /var/lib/opflex/files/services:/var/lib/opflex-agent-ovs/services:shared,z
          - /var/lib/opflex/files/ids:/var/lib/opflex-agent-ovs/ids:shared,z
          - /var/lib/opflex/files/mcast:/var/lib/opflex-agent-ovs/mcast:shared,z
          - /var/lib/opflex/files/droplog:/var/lib/opflex-agent-ovs/droplog:shared,z
          - /var/lib/opflex/files/faults:/var/lib/opflex-agent-ovs/faults:shared,z
          - /var/lib/opflex/files/policy:/var/lib/opflex-agent-ovs/policy:shared,z
          - /var/lib/opflex/files/restarts:/var/lib/opflex-agent-ovs/restarts:shared,z
          - /var/lib/opflex/sockets:/var/lib/opflex-agent-ovs/sockets:shared,z
        description: List of volumes in a mount point form.
        type: list
      edpm_neutron_dhcp_agent_AGENT_root_helper:
        default: 'sudo neutron-rootwrap /etc/neutron/rootwrap.conf'
        description: ''
        type: str
      edpm_neutron_dhcp_agent_AGENT_report_interval:
        default: 300
        description: ''
        type: int
